import = [
    "~/.config/alacritty/themes/catpuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 9.0

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[scrolling]
history = 0

[window.padding]
x = 4
y = 3

[window]
opacity = 0.9

